name: secp256k1-haskell
version: 1.4.4
synopsis: Bindings for secp256k1
description: Sign and verify signatures using the secp256k1 library.
category: Crypto
author: JP Rupp
maintainer: jprupp@protonmail.ch
license: MIT
license-file: LICENSE
github: jprupp/secp256k1-haskell
homepage: http://github.com/jprupp/secp256k1-haskell#readme
extra-source-files:
  - CHANGELOG.md
dependencies:
  - base >=4.9 && <5
  - base16 >=1.0
  - bytestring >=0.10.8
  - entropy >=0.3.8
  - deepseq >=1.4.2
  - hashable >=1.2.6
  - QuickCheck >=2.9.2
  - string-conversions >=0.4
  - unliftio-core >=0.1.0
library:
  source-dirs: src
  generated-exposed-modules:
    - Paths_secp256k1_haskell
  pkg-config-dependencies:
    - libsecp256k1
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    verbatim:
      build-tool-depends:
          hspec-discover:hspec-discover
    dependencies:
      - hspec
      - secp256k1-haskell
      - monad-par
      - mtl
      - HUnit
